### ISSUE TITLE
Gameloop

### ISSUE THREAD

**Issue by bferijan** [se2-monopoly-ss20-v2/monopoly#13]
**Is your feature request related to a problem? Please describe.**
Work on the general functionality of turns - for example check for game over scenarios, end and start turns correctly, update relevant player information etc. 

**Describe the solution you'd like**
This is a rather large feature/issue. It will require:
- Gathering information on possible game states
- The possibility of starting, ending and extending turns of players (Definition of a turn)
- Keeping track of changes on the board and player information 
- Checking possible options a player has on a turn (e.g. taking up a mortgage)
- Finally implemententing the basic loop that constantly updates at the start/end of a turn

**Comment by Chfaeser** [comment]
The general gameloop has been worked out and was tested locally. It hasn't been implemented this sprint due to messing with too many ongoing features. Due to missing some methods for the turn logic the gameloop would also serve no purpose in the current version of the game. Once the server functionality has been expanded implementing the gameloop will be a high priority. 

This is a short summary of the gameloop and how it will function. The full implementation will follow.

[Gameloop Summary.docx](https://github.com/se2-monopoly-ss20-v2/monopoly/files/4655578/Gameloop.Summary.docx)

**Comment by Chfaeser** [comment]
This has been worked out through the gamestate which solved the gameloop issue
